insert into cake2cribs.realtors values (4097,'Murphy Property',\N,\N,\N);
insert into cake2cribs.realtors values (4098,'Allmand',\N,\N,\N);
insert into cake2cribs.realtors values (4099,'American Campus',\N,\N,\N);
insert into cake2cribs.realtors values (4100,'Arbor ',\N,\N,\N);
insert into cake2cribs.realtors values (4101,'Arbor Stone ',\N,\N,\N);
insert into cake2cribs.realtors values (4102,'Arch Realty',\N,\N,\N);
insert into cake2cribs.realtors values (4103,'Bartonbrook',\N,\N,\N);
insert into cake2cribs.realtors values (4104,'Cabrio Properties',\N,\N,\N);
insert into cake2cribs.realtors values (4105,'Campus Management',\N,\N,\N);
insert into cake2cribs.realtors values (4106,'Campus Realty',\N,\N,\N);
insert into cake2cribs.realtors values (4107,'Cappo/Deinco',\N,\N,\N);
insert into cake2cribs.realtors values (4108,'CareOne',\N,\N,\N);
insert into cake2cribs.realtors values (4109,'Carlson Properties',\N,\N,\N);
insert into cake2cribs.realtors values (4110,'CMB',\N,\N,\N);
insert into cake2cribs.realtors values (4111,'Copi Properties',\N,\N,\N);
insert into cake2cribs.realtors values (4112,'Gottschalk',\N,\N,\N);
insert into cake2cribs.realtors values (4113,'Gruber',\N,\N,\N);
insert into cake2cribs.realtors values (4114,'Hill Street',\N,\N,\N);
insert into cake2cribs.realtors values (4115,'Huron Tower Apts.',\N,\N,\N);
insert into cake2cribs.realtors values (4116,'IPM',\N,\N,\N);
insert into cake2cribs.realtors values (4117,'J. Keller Properties',\N,\N,\N);
insert into cake2cribs.realtors values (4118,'Jaeger Properties',\N,\N,\N);
insert into cake2cribs.realtors values (4119,'JMS  ',\N,\N,\N);
insert into cake2cribs.realtors values (4120,'Jones ',\N,\N,\N);
insert into cake2cribs.realtors values (4121,'Keys Management',\N,\N,\N);
insert into cake2cribs.realtors values (4122,'Madison Company',\N,\N,\N);
insert into cake2cribs.realtors values (4123,'Metro Property ',\N,\N,\N);
insert into cake2cribs.realtors values (4124,'Michigan Rental',\N,\N,\N);
insert into cake2cribs.realtors values (4125,'Old Town Realty',\N,\N,\N);
insert into cake2cribs.realtors values (4126,'Oppenheimer  ',\N,\N,\N);
insert into cake2cribs.realtors values (4127,'Peppers Properties',\N,\N,\N);
insert into cake2cribs.realtors values (4128,'Pine Valley',\N,\N,\N);
insert into cake2cribs.realtors values (4129,'PMSI',\N,\N,\N);
insert into cake2cribs.realtors values (4130,'Prime Housing',\N,\N,\N);
insert into cake2cribs.realtors values (4131,'Smiley Properties',\N,\N,\N);
insert into cake2cribs.realtors values (4132,'Sterling University',\N,\N,\N);
insert into cake2cribs.realtors values (4133,'Tree City ',\N,\N,\N);
insert into cake2cribs.realtors values (4134,'U. of Michigan',\N,\N,\N);
insert into cake2cribs.realtors values (4135,'University Places',\N,\N,\N);
insert into cake2cribs.realtors values (4136,'University Towers ',\N,\N,\N);
insert into cake2cribs.realtors values (4137,'Varsity ',\N,\N,\N);
insert into cake2cribs.realtors values (4138,'Wessinger Properties',\N,\N,\N);
insert into cake2cribs.realtors values (4139,'Willowtree Apts.',\N,\N,\N);
insert into cake2cribs.realtors values (4140,'Wilson White Company',\N,\N,\N);
insert into cake2cribs.realtors values (4141,'Zaragon ',\N,\N,\N);
insert into cake2cribs.realtors values (4142,'Panhellenic',\N,\N,\N);
insert into cake2cribs.realtors values (4143,'Interfraternity',\N,\N,\N);
insert into cake2cribs.realtors values (4144,'Post Realty',\N,\N,\N);
