// Generated by CoffeeScript 1.4.0
(function() {

  A2Cribs.Account = (function() {

    function Account() {}

    Account.setupUI = function() {
      var url,
        _this = this;
      url = myBaseUrl + "university/getAll/";
      return $.get(url, function(data) {
        _this.UniversityData = JSON.parse(data);
        _this.UniversityNames = [];
        _this.UniversityID = [];
        _.each(_this.UniversityData, function(value, key, list) {
          _this.UniversityNames[key] = value['University']['name'];
          return _this.UniversityID[key] = value['University']['id'];
        });
        return $('#university').typeahead({
          source: _this.UniversityNames
        });
      });
    };

    return Account;

  })();

}).call(this);
