// Generated by CoffeeScript 1.6.3
/*
Class Analytics
Wrapper class to handle the interactions
with google analytics event tracking
*/


(function() {
  A2Cribs.Analytics = (function() {
    var _this = this;

    function Analytics() {}

    $(document).on("logged_in", function(event, user) {
      return Analytics.Event("Logged In", {
        "name": user != null ? user.name : void 0,
        "email": user != null ? user.email : void 0
      });
    });

    return Analytics;

  }).call(this);

}).call(this);
