// Generated by CoffeeScript 1.4.0
(function() {

  A2Cribs.Dashboard = (function() {

    function Dashboard() {}

    Dashboard.SetupUI = function() {
      var _this = this;
      $(window).resize(function() {
        return _this.SizeContent();
      });
      this.SizeContent();
      return $('.content-header').each(function(index, element) {
        var class_name, content, content_header;
        content_header = $(element);
        class_name = content_header.attr('classname');
        content = $('.' + class_name + '-content');
        $(element).click(function(event) {
          var show_content;
          if ($(event.target).hasClass('toggle-drop-down')) {
            show_content = content_header.next('.drop-down').is(':hidden');
            return _this.SlideDropDown(content_header, show_content);
          } else {
            _this.SlideDropDown(content_header, true);
            return _this.ShowHideContent(content, true);
          }
        });
        return typeof content_header.next === "function" ? content_header.next('.drop-down').find('.drop-down-list').click(function() {
          return _this.ShowHideContent(content, true);
        }) : void 0;
      });
    };

    Dashboard.SizeContent = function() {
      var main_content, middle_content;
      main_content = $('#main_content');
      middle_content = $('#middle_content');
      return main_content.css('height', (window.innerHeight - main_content.offset().top) + 'px');
    };

    Dashboard.SlideDropDown = function(content_header, show_content) {
      var dropdown, toggle_icon;
      dropdown = content_header.next('.drop-down');
      toggle_icon = content_header.children('i')[0];
      $(toggle_icon).toggleClass('icon-caret-right', !show_content).toggleClass('icon-caret-down', show_content);
      $(content_header).toggleClass('shadowed', show_content).toggleClass('expanded', show_content).toggleClass('minimized', !show_content);
      if (show_content) {
        return dropdown.slideDown('fast');
      } else {
        return dropdown.slideUp('fast');
      }
    };

    Dashboard.ShowHideContent = function(content, show) {
      return content.toggleClass('hidden', !show);
    };

    return Dashboard;

  })();

}).call(this);
