// Generated by CoffeeScript 1.4.0

/*
Static class handling all Favorites functionality.
Call functions using FavoritesManager.FunctionName()
*/


(function() {

  A2Cribs.FavoritesManager = (function() {

    function FavoritesManager() {}

    FavoritesManager.FavoritesListingIds = [];

    FavoritesManager.FavoritesVisible = false;

    /*
    	Add a favorite
    */


    FavoritesManager.AddFavorite = function(listing_id, button) {
      return $.ajax({
        url: myBaseUrl + "Favorites/AddFavorite/" + listing_id,
        type: "POST",
        context: this,
        success: function(response) {
          return A2Cribs.FavoritesManager.AddFavoriteCallback(response, listing_id, button);
        }
      });
    };

    FavoritesManager.AddFavoriteCallback = function(response, listing_id, button) {
      response = JSON.parse(response);
      if (response.success === void 0) {
        if (response.error.message !== void 0) {
          return A2Cribs.UIManager.Alert(response.error.message);
        } else {
          return A2Cribs.UIManager.Alert("There was an error adding your favorite. Contact help@cribspot.com if the error persists.");
        }
      } else {
        this.FavoritesListingIds.push(listing_id);
        if (button != null) {
          $(button).attr('onclick', 'A2Cribs.FavoritesManager.DeleteFavorite(' + listing_id + ', this);');
          $(button).attr('title', 'Delete from Favorites');
          $(button).addClass('active');
          return this._setFavoriteCount();
        }
      }
    };

    /*
    	Delete a favorite
    */


    FavoritesManager.DeleteFavorite = function(listing_id, button) {
      return $.ajax({
        url: myBaseUrl + "Favorites/DeleteFavorite/" + listing_id,
        type: "POST",
        context: this,
        success: function(response) {
          return A2Cribs.FavoritesManager.DeleteFavoriteCallback(response, listing_id, button);
        }
      });
    };

    FavoritesManager.DeleteFavoriteCallback = function(response, listing_id, button) {
      var index;
      response = JSON.parse(response);
      if (response.error !== void 0) {
        return A2Cribs.UIManager.Alert(response.error.message);
      } else {
        index = A2Cribs.FavoritesManager.FavoritesListingIds.indexOf(listing_id);
        if (index !== -1) {
          A2Cribs.FavoritesManager.FavoritesListingIds.splice(index);
        }
        if (button != null) {
          $(button).attr('onclick', 'A2Cribs.FavoritesManager.AddFavorite(' + listing_id + ', this);');
          $(button).attr('title', 'Add to Favorites');
          $(button).removeClass('active');
          return this._setFavoriteCount();
        }
      }
    };

    /*
    	response contains a list of listing_ids that have been favorited by the logged-in user
    */


    FavoritesManager.InitializeFavorites = function(response) {
      var listing_id, listing_ids, _i, _len;
      if (response === null || response === void 0) {
        return;
      }
      listing_ids = JSON.parse(response);
      for (_i = 0, _len = listing_ids.length; _i < _len; _i++) {
        listing_id = listing_ids[_i];
        A2Cribs.FavoritesManager.FavoritesListingIds.push(parseInt(listing_id));
      }
      return this._setFavoriteCount();
    };

    /*
    	Loads all favorites for current user.
    */


    FavoritesManager.LoadFavorites = function() {
      return $.ajax({
        url: myBaseUrl + "Favorites/LoadFavorites",
        type: "GET",
        context: this,
        success: A2Cribs.FavoritesManager.InitializeFavorites
      });
    };

    /*
    	Called when user clicks the heart icon in the header.
    	Toggles visibility of markers where user has favorited a listing.
    */


    FavoritesManager.ToggleFavoritesVisibility = function(button) {
      var all_listings, all_markers, listing, listing_id, marker, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _m, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
      $(button).toggleClass('active');
      if ((_ref = A2Cribs.HoverBubble) != null) {
        _ref.Close();
      }
      if ((_ref1 = A2Cribs.ClickBubble) != null) {
        _ref1.Close();
      }
      all_markers = A2Cribs.UserCache.Get('marker');
      all_listings = A2Cribs.UserCache.Get('listing');
      if (!A2Cribs.FavoritesManager.FavoritesVisible) {
        $("#FavoritesHeaderIcon").addClass("pressed");
        for (_i = 0, _len = all_markers.length; _i < _len; _i++) {
          marker = all_markers[_i];
          if ((_ref2 = marker.GMarker) != null) {
            _ref2.setVisible(false);
          }
        }
        for (_j = 0, _len1 = all_listings.length; _j < _len1; _j++) {
          listing = all_listings[_j];
          listing.visible = false;
        }
        _ref3 = A2Cribs.FavoritesManager.FavoritesListingIds;
        for (_k = 0, _len2 = _ref3.length; _k < _len2; _k++) {
          listing_id = _ref3[_k];
          listing = A2Cribs.UserCache.Get('listing', listing_id);
          marker = A2Cribs.UserCache.Get('marker', listing.marker_id);
          if ((_ref4 = marker.GMarker) != null) {
            _ref4.setVisible(true);
          }
          listing.visible = true;
        }
      } else {
        for (_l = 0, _len3 = all_markers.length; _l < _len3; _l++) {
          marker = all_markers[_l];
          if (marker != null) {
            if ((_ref5 = marker.GMarker) != null) {
              _ref5.setVisible(true);
            }
          }
        }
        for (_m = 0, _len4 = all_listings.length; _m < _len4; _m++) {
          listing = all_listings[_m];
          listing.visible = true;
        }
        $("#FavoritesHeaderIcon").removeClass("pressed");
      }
      A2Cribs.Map.GMarkerClusterer.repaint();
      return A2Cribs.FavoritesManager.FavoritesVisible = !A2Cribs.FavoritesManager.FavoritesVisible;
    };

    FavoritesManager.FavoritesVisibilityIsOn = function() {
      return $("#FavoritesHeaderIcon").hasClass("pressed");
    };

    /*
    	Inserts the recent favorite into the favorites tab
    */


    FavoritesManager._insertIntoFavoriteDiv = function(listing_id) {
      var content, marker, sublet, template, title;
      if (this.FavoritesCache.size === 1) {
        $('#noFavorites').hide();
      }
      sublet = A2Cribs.Map.IdToSubletMap[listing_id];
      marker = A2Cribs.Map.IdToMarkerMap[sublet.MarkerId];
      title = marker.Title ? marker.Title : marker.Address;
      template = $('#favoriteTemplate');
      template.find('.favoriteDiv').attr({
        id: "favoriteDiv" + listing_id
      });
      template.find('.favoritesAddress').html(title);
      template.find('.removeButton').attr({
        onclick: "A2Cribs.FavoritesManager.DeleteFavorite(" + listing_id + ")"
      });
      template.find('a').attr({
        href: listing.Url
      });
      template.find('#price').html(listing.Rent ? '$' + listing.Rent : "???");
      template.find('#beds').html(listing.Beds + (listing.Beds > 1 ? " Beds" : " Bed"));
      template.find('#baths').html(listing.Baths + (listing.Baths > 1 ? " Baths" : " Bath"));
      template.find('#payMonth').html(listing.LeaseRange);
      template.find('#aptType').html(listing.UnitType);
      template.find('#electric').find('div').addClass(listing.Electric ? "electric_selected" : "electric_unselected");
      template.find('#heat').find('div').addClass(listing.Heat ? "heat_selected" : "heat_unselected");
      template.find('#water').find('div').addClass(listing.Water ? "water_selected" : "water_unselected");
      template.find('#furnished').find('div').addClass(listing.Furnished ? "furnished_selected" : "furnished_unselected");
      template.find('#parking').find('div').addClass(listing.Parking ? "parking_selected" : "parking_unselected");
      template.find('#ac').find('div').addClass(listing.Air ? "ac_selected" : "ac_unselected");
      content = $('#favoriteTemplate').html();
      return $('#personalFavoritesList').append(content);
    };

    FavoritesManager._setFavoriteCount = function() {
      if (this.FavoritesListingIds.length === 0) {
        return $(".favorite_count").hide();
      } else {
        return $(".favorite_count").show().text(this.FavoritesListingIds.length);
      }
    };

    /*
    	Removes the recent favorite into the favorites tab
    */


    FavoritesManager._removeFromFavoriteDiv = function(listing_id) {
      $('#personalFavoritesList').find('#favoriteDiv' + listing_id).remove();
      if (this.FavoritesCache.size === 0) {
        return $('#noFavorites').show();
      }
    };

    FavoritesManager._insertFavoriteCache = function(listing_id) {
      this.FavoritesCache[listing_id] = true;
      ++this.FavoritesCache.size;
      return $('#numFavorites').html(this.FavoritesCache.size);
    };

    FavoritesManager._removeFavoriteCache = function(listing_id) {
      this.FavoritesCache[listing_id] = null;
      --this.FavoritesCache.size;
      return $('#numFavorites').html(this.FavoritesCache.size);
    };

    return FavoritesManager;

  })();

}).call(this);
