// Generated by CoffeeScript 1.4.0
(function() {

  A2Cribs.FLDash = (function() {

    function FLDash(Widget) {
      var _this = this;
      this.Widget = Widget;
      this.Widget.find(".listings_list").click(function(event) {
        return _this.loadForm($(event.target));
      });
      this.Widget.find(".feature-listing").click(function() {
        return _this.featureListing();
      });
      this.FL = null;
      this.CurrSelected = null;
      this.FL_Form = $('.featured-listing-order-item').first();
      this.FL_Form.find(".total-tally").hide();
    }

    FLDash.prototype.loadForm = function(listing) {
      var addr, id, _ref;
      this.CurrSelected = listing;
      id = listing.data('id');
      addr = listing.data('addr');
      if ((_ref = this.FL) != null) {
        _ref.clear();
      }
      this.FL = new A2Cribs.Order.FeaturedListing(this.FL_Form, id, addr);
      return this.Widget.find(".fl_form").fadeIn("fast");
    };

    FLDash.prototype.featureListing = function() {
      var post_data, url,
        _this = this;
      if (!(this.FL != null)) {
        return;
      }
      url = myBaseUrl + "order/suFeatureListing";
      post_data = {
        'orderItem': JSON.stringify(this.FL.getOrderItem())
      };
      return $.post(url, post_data, function(data) {
        var response;
        response = JSON.parse(data);
        if (!(response != null)) {
          return alertify.error("Something went horribly wrong");
        } else if (response.success) {
          alertify.success(response.msg);
          return _this.Widget.find(".fl_form").fadeOut("fast");
        } else {
          return alertify.error(response.msg);
        }
      });
    };

    return FLDash;

  })();

}).call(this);
