// Generated by CoffeeScript 1.6.3
(function() {
  A2Cribs.Hotlist = (function() {
    Hotlist.Initialize = function() {
      var el;
      el = $('#friends-list');
      return A2Cribs.HotlistObj = new A2Cribs.Hotlist(el);
    };

    Hotlist.call = function(friend, action) {
      var data, deferred, url,
        _this = this;
      url = myBaseUrl + ("friends/hotlist/" + action);
      deferred = new $.Deferred();
      data = {
        friend_id: friend
      };
      $.ajax({
        url: url,
        data: data,
        type: "POST",
        success: function(response) {
          return deferred.resolve(JSON.parse(response));
        },
        error: function() {
          return deferred.reject();
        }
      });
      return deferred.promise();
    };

    function Hotlist(DOMRoot) {
      this.DOMRoot = DOMRoot;
      this.template = _.template(A2Cribs.Hotlist.templateHTML);
      this.setup();
    }

    Hotlist.prototype.setup = function() {
      var _this = this;
      $.when(this.get()).then((function(data, status, jqXHR) {
        data = {
          friends: data
        };
        return _this.render(data);
      }), (function(data, status, jqXHR) {
        return alert(data);
      }));
      return this;
    };

    Hotlist.prototype.render = function(data) {
      this.DOMRoot.html(this.template(data));
      return $('.friend-adder .typeahead').typeahead({
        source: function(query, process) {
          if (query.match(/^.+\@.+\..+$/)) {
            console.log(encodeURIComponent(query));
            return $.ajax({
              type: 'get',
              url: myBaseUrl + 'users/getbyname',
              data: {
                name: query
              },
              success: function(data) {
                var namelist, response_data;
                response_data = JSON.parse(data);
                namelist = response_data.map(function(u) {
                  return "" + u.User.email + " - <em>" + u.User.first_name + " " + u.User.last_name + "</em> <img src='http://placehold.it/20x20'/>";
                });
                process(namelist);
                return console.log(namelist);
              },
              fail: function(data) {
                return console.log(data);
              }
            });
          }
        },
        updater: function(item) {
          return item.split(' ')[0];
        }
      });
    };

    Hotlist.prototype.get = function() {
      var deferred,
        _this = this;
      deferred = new $.Deferred();
      $.ajax({
        url: myBaseUrl + "friends/hotlist/",
        type: "GET",
        success: function(data) {
          return deferred.resolve(JSON.parse(data));
        },
        error: function() {
          return deferred.reject();
        }
      });
      return deferred.promise();
    };

    Hotlist.prototype.remove = function(friend) {
      var _this = this;
      return $.when(A2Cribs.Hotlist.call(friend, 'remove')).then((function(data, status, jqXHR) {
        data = {
          friends: data
        };
        return _this.render(data);
      }));
    };

    Hotlist.prototype.add = function(friend) {
      var _this = this;
      return $.when(A2Cribs.Hotlist.call(friend, 'add')).then((function(data, status, jqXHR) {
        data = {
          friends: data
        };
        return _this.render(data);
      }));
    };

    Hotlist.templateHTML = "<div id='share-all'></div>\n<ul class='friends'>\n  <% _.each(friends, function(elem, idx, list) { %>\n    <li class='friend'>\n      <%=elem.first_name%> <%=elem.last_name%> <a href = '#' onClick='A2Cribs.HotlistObj.remove(<%=elem.id%>)'>x</a>\n    </li>\n  <% }); %>\n</ul>\n<div class='friend-adder'>\n    <input class='typeahead' type='text' autocomplete='off'></input>\n</div>";

    return Hotlist;

  })();

}).call(this);
