// Generated by CoffeeScript 1.6.1
(function() {

  A2Cribs.Housemate = (function() {

    function Housemate(SubletId, Enrolled, Major, Seeking, GradType, Gender) {
      this.SubletId = SubletId;
      this.Enrolled = Enrolled;
      this.Major = Major;
      this.Seeking = Seeking;
      this.GradType = GradType;
      this.Gender = Gender;
    }

    return Housemate;

  })();

}).call(this);
