// Generated by CoffeeScript 1.4.0

/*
HoverBubble class
Wrapper for google infobubble
*/


(function() {

  A2Cribs.HoverBubble = (function() {

    function HoverBubble() {}

    /*
    	Constructor
    	-creates infobubble object
    */


    HoverBubble.Init = function(map) {
      var obj;
      this.template = $(".hover-bubble:first").parent();
      obj = {
        map: map,
        arrowStyle: 0,
        arrowPosition: 20,
        shadowStyle: 0,
        borderRadius: 5,
        arrowSize: 17,
        borderWidth: 0,
        disableAutoPan: true,
        padding: 0,
        disableAnimation: true
      };
      this.InfoBubble = new InfoBubble(obj);
      this.InfoBubble.hideCloseButton();
      this.InfoBubble.setBackgroundClassName("map_bubble");
      return this.template.find(".close_button").attr("onclick", "A2Cribs.HoverBubble.Close();");
    };

    /*
    	Opens the tooltip given a marker, with popping animation
    */


    HoverBubble.Open = function(marker) {
      if (marker) {
        this.SetContent(marker);
        return this.InfoBubble.open(A2Cribs.Map.GMap, marker.GMarker);
      }
    };

    /*
    	Refreshes the tooltip with the new content, no animation
    */


    HoverBubble.Refresh = function() {
      return this.InfoBubble.open();
    };

    /*
    f	Closes the tooltip, no animation
    */


    HoverBubble.Close = function() {
      return this.InfoBubble.close();
    };

    /*
    	Sets the content of the tooltip
    */


    HoverBubble.SetContent = function(marker) {
      var listing, listing_info, listings, unit_template, _i, _len;
      listings = A2Cribs.UserCache.GetAllAssociatedObjects("listing", "marker", marker.GetId());
      this.template.find(".building_type").text(marker.GetBuildingType());
      this.template.find(".unit_div").empty();
      for (_i = 0, _len = listings.length; _i < _len; _i++) {
        listing = listings[_i];
        if (!(listing.visible != null) || listing.visible) {
          listing_info = A2Cribs.UserCache.Get(A2Cribs.Map.ACTIVE_LISTING_TYPE, listing.GetId());
          unit_template = $("<div />", {
            "class": "unit"
          });
          unit_template.attr("onclick", "A2Cribs.ClickBubble.Open(" + (listing.GetId()) + ")");
          $("<div />", {
            "class": "beds",
            text: listing_info["beds"]
          }).appendTo(unit_template);
          $("<div />", {
            "class": "bed_desc",
            text: (listing_info["beds"] != null) === 1 ? "Bed" : "Beds"
          }).appendTo(unit_template);
          $("<div />", {
            "class": "rent",
            text: "$" + listing_info["rent"]
          }).appendTo(unit_template);
          this.template.find(".unit_div").append(unit_template);
        }
      }
      return this.InfoBubble.setContent(this.template.html());
    };

    HoverBubble.resolveDate = function(minDate, maxDate) {
      var maxSplit, minSplit;
      minSplit = minDate.split("-");
      maxSplit = maxDate.split("-");
      return +minSplit[1] + "/" + +minSplit[2] + "-" + +maxSplit[1] + "/" + +maxSplit[2];
    };

    return HoverBubble;

  })();

}).call(this);
