// Generated by CoffeeScript 1.4.0
(function() {

  A2Cribs.Rentals = (function() {

    function Rentals() {}

    Rentals.prototype.SetupUI = function() {
      /*
      		********************* TODO **********************
      */

    };

    Rentals.prototype.Open = function(rental_ids) {
      /*
      		********************* TODO **********************
      */

    };

    Rentals.prototype.Save = function() {
      /*
      		********************* TODO **********************
      */

    };

    Rentals.prototype.Copy = function(rental_ids) {
      /*
      		********************* TODO (Not first priority) *
      */

    };

    Rentals.prototype.Delete = function(rental_ids) {
      /*
      		********************* TODO **********************
      */

    };

    Rentals.prototype.Create = function() {
      /*
      		********************* TODO **********************
      */

    };

    Rentals.prototype.PopulateGrid = function(rental_ids) {
      /*
      		********************* TODO **********************
      */

    };

    return Rentals;

  })();

}).call(this);
