// Generated by CoffeeScript 1.4.0
(function() {

  A2Cribs.ShoppingCart = (function() {

    function ShoppingCart(Widget) {
      var _this = this;
      this.Widget = Widget;
      this.Widget.on('click', '.edit', function(event) {
        var index;
        index = $(event.currentTarget).attr('id');
        return _this.edit(index);
      });
      this.Widget.find('.fl-cart-item').each(function(index, element) {
        $(element).find(".edit").click(function() {
          return _this.edit(index);
        });
        return $(element).find(".remove").click(function() {
          return _this.remove(index);
        });
      });
      this.Widget.find('.buy').click(function() {
        return A2Cribs.Order.BuyCart();
      });
      this.Widget.find('.hide-edit').click(function() {
        return $('.edit-form').fadeOut();
      });
      this.Widget.find('.save').click(function() {
        return _this.save(_this.EditingIndex);
      });
      this.Editing = false;
      this.EditingIndex = -1;
      this.orderItem = null;
      this.refresh();
    }

    ShoppingCart.prototype.remove = function(index) {
      var data, url,
        _this = this;
      url = myBaseUrl + "shoppingCart/remove";
      data = {
        'index': index
      };
      return $.post(url, data, function(response) {
        var success;
        success = JSON.parse(response).success;
        if (success) {
          return _this.Widget.find('.fl-cart-item').get(index).remove();
        } else {
          return alertify.error("Removing item " + (index + 1) + " failed");
        }
      });
    };

    ShoppingCart.prototype.refresh = function() {
      return $('.orderItems > tbody').load('/shoppingCart/get', function() {
        return $('table.orderItems').fadeIn();
      });
    };

    ShoppingCart.prototype.edit = function(index) {
      this.orderItem = new A2Cribs.Order.FeaturedListing($('.featured-listing-order-item').first(), {
        address: '123 Fake Street',
        listing_id: 12,
        dates: ['6/26/13']
      });
      $('.edit-form').fadeIn('fast');
      return this.EditingIndex = index;
    };

    ShoppingCart.prototype.save = function() {
      var data,
        _this = this;
      if (this.EditingIndex >= 0) {
        data = {
          orderItem: JSON.stringify(this.orderItem.getOrderItem()),
          index: this.EditingIndex
        };
        return $.post('/shoppingCart/edit', data, function(response) {
          data = JSON.parse(response);
          if (data.success) {
            alertify.success("Save Successful");
            return _this.refresh();
          } else {
            return alertify.error(data.msg);
          }
        });
      }
    };

    return ShoppingCart;

  })();

}).call(this);
