// Generated by CoffeeScript 1.4.0
(function() {

  A2Cribs.SubletAdd = (function() {

    function SubletAdd() {}

    SubletAdd.setupUI = function() {
      var _this = this;
      return $('#goToStep2').click(function(e) {
        e.preventDefault();
        return _this.subletAddStep1();
      });
    };

    SubletAdd.subletAddStep1 = function() {
      var request_data, url,
        _this = this;
      url = "sublets/ajax_add_create";
      request_data = {
        Sublet: {
          university: $('#universitiesInput').val(),
          building_type_id: $('#SubletBuildingTypeId').val(),
          name: $('#SubletName').val(),
          latitude: $('#updatedLat').text(),
          longitude: $('#updatedLong').text()
        }
      };
      return $.post(url, request_data, function(response) {
        var data;
        console.log(response);
        data = JSON.parse(response);
        return console.log(data);
      });
    };

    return SubletAdd;

  })();

}).call(this);
