insert into schools values(0, 'University of Michigan', "Ann Arbor, MI", 0, 0, 0, 0);
insert into schools values(1, 'University of Iowa', "De Moines, IA", 0, 0, 0, 0);
insert into schools values(2, 'Pennsylvania State University', "State College, PA", 0, 0, 0, 0);
insert into schools values(3, 'Michigan State University', "East Lansing, MI", 0, 0, 0, 0);
insert into schools values(4, 'Rutgers University', "Some City, NJ", 0, 0, 0, 0);
insert into schools values(5, 'Indiana University', "Bloomington, ID", 0, 0, 0, 0);
insert into schools values(6, 'University of Wisconsin', "Madison, WI", 0, 0, 0, 0);
insert into schools values(7, 'University of Illinois', "Champagne, IL", 0, 0, 0, 0);
insert into schools values(8, 'Northwestern University', "Evanston, IL", 0, 0, 0, 0);
insert into schools values(9, 'Stanford University', "Palo Alto, CA", 0, 0, 0, 0);
insert into schools values(10, 'University of Pittsburgh', "Pittsburgh, PA", 0, 0, 0, 0);
insert into schools values(11, 'University of Maryland', "College Park, MD", 0, 0, 0, 0);
insert into schools values(12, 'Duke University', "Durham, NC", 0, 0, 0, 0);
insert into schools values(13, 'New York University', "New York, NY", 0, 0, 0, 0);
insert into schools values(14, 'Eastern Michigan University', "Ypsilanti, MI", 0, 0, 0, 0);
