// Generated by CoffeeScript 1.4.0
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  A2Cribs.Landing = (function() {

    function Landing() {}

    Landing.Submit = function() {
      var location;
      location = $("#locations").val();
      if (__indexOf.call(locations, location) >= 0) {
        return alert("Finding listings for " + location);
      } else {
        return alert(location + " is not a valid location.");
      }
    };

    return Landing;

  })();

}).call(this);
